# Compose xrdp server
version: '3.0'

services:

#######################################
# Docker in Docker Server
#######################################

  shared-docker:
    image: docker:stable-dind
    command: --storage-driver=overlay2
    hostname: shared-docker
    privileged: True
    volumes:
      - shared-docker-data:/var/lib/docker
  
######################################
#  XRDP / SSH Server
######################################

  xrdp:
    hostname: xrdp
    image: danielguerra/ubuntu-xrdp-docker
    shm_size: 1g
    privileged: true
    links:
      - shared-docker:docker
    volumes:
      - xrdp-home:/home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '2289:3389'
      - '2222:22'
    environment:
      CHROMA_USER: Chroma_T610_Dikey
      CHROMA_USER_OS: UB20
    networks:
      - ipv6_net

######################################
# Volumes
######################################
volumes:
  shared-docker-data:
  xrdp-home:
  
networks:
  ipv6_net:
    enable_ipv6: true
    driver: bridge
    # driver_opts is here just a precaution as some docker compose versions do not process the above "enable_ipv6"
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      #- subnet: 172.16.238.0/24
      #  gateway: 172.16.238.1
       - subnet: 2001:db8:a::/64
         gateway: 2001:db8:a::1
  
  
  